### ISSUE TITLE
Bug:  Incorrect script update logic

### ISSUE THREAD

**Issue by click0** [pretzelhands/jinx#7]
### Expected Behavior

We expect that users of the script will see minor updates, including security fixes.

### Actual Behavior

If there are minor updates without release, then users of these minor updates will not see the regular means. Including the last version of the script - 0.3.1.

Therefore it is necessary to do these minor updates as releases.

I also pay attention that deleting old files is not entirely correct, all of a sudden, something goes wrong and the user will receive a "broken" script.
I suggest renaming old files and directories, for example:
`mv $JINX_BIN $JINX_BIN.back.$JINX_VERSION`
and
`mv $JINX_ETC $JINX_ETC.back.$JINX_VERSION`

### Steps to Reproduce the Problem

* bash <(curl -s https://raw.githubusercontent.com/pretzelhands/jinx/master/installer)
* jinx update
* grep "JINX_VERSION" /usr/local/bin/jinx

### Specifications

* **`jinx` version:**
* **OS and version:**
* **nginx version:**

**Comment by pretzelhands** [comment]
Updating now makes backups of older versions instead of just deleting it. Will be released with the upcoming 0.3.1 release. 👍
