### ISSUE TITLE
Bug: jinx_get_yesterday_timestamp() assumes GNU coreutils

### ISSUE THREAD

**Issue by Michcioperz** [pretzelhands/jinx#9]
### Expected Behavior

`jinx_get_yesterday_timestamp()` should return yesterday's timestamp on Linux.

### Actual Behavior

It won't work on systems where `date` command is provided by Busybox, such as on Alpine Linux (a distro commonly used for containers, among other things), because what's expected of `date` here is a GNU extension beyond what POSIX requires.

![QEMU screenshot](https://user-images.githubusercontent.com/3064202/51863231-c61a4400-2340-11e9-966e-52368eb81dee.png)

### Steps to Reproduce the Problem

* boot up Alpine Linux
* try to use commands from `jinx_get_yesterday_timestamp()`

### Specifications

* **`jinx` version:** 0.3.1
* **OS and version:** Alpine Linux 3.8
* **nginx version:** n/a

**Comment by click0** [comment]
Please show output:
`env`

**Comment by Michcioperz** [comment]
```bash
USER=root
PAGER=less
PWD=/root
HOME=/root
CHARSET=UTF-8
SHELL=/bin/bash
TERM=vt102
SHLVL=1
LOGNAME=root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PS1=\h:\w\$
_=/usr/bin/env
```

I thought about why you asked for that - default shell in Alpine is ash and jinx is a bash project - but I installed bash to check and the commands have the same results. I think `date` is not a bash builtin, so this doesn't seem to make a difference.

**Comment by click0** [comment]
Please show output:
`date --date='1 days ago' +%s`
`date --date='1 day ago' +%s`
`date +%s`
`uname -s`
and
`cat /etc/*-release`

**Comment by Michcioperz** [comment]
`date --date='1 days ago' +%s`: ```date: invalid date '1 days ago'```

`date --date='1 day ago' +%s`: ```date: invalid date: '1 day ago'```

`date +%s`: ```1548713526```

`uname -s`: ```Linux```

`uname -a`: ```Linux localhost 4.14.89-0-virt #1-Alpine SMP Tue Dec 18 16:30:58 UTC 2018 x86_64 Linux```

`cat /etc/alpine-release`: ```3.8.2```

`cat /etc/os-release`:
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.2
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

**Comment by Michcioperz** [comment]
If you want to get into Alpine quickly, I recommend spinning up a virtual machine from [alpine-virt-3.8.2-x86_64.iso](http://dl-cdn.alpinelinux.org/alpine/v3.8/releases/x86_64/alpine-virt-3.8.2-x86_64.iso), then logging in as root without password, running `setup-alpine` and answering its questions until after you've chosen a mirror for package manager (you need to get this far in order to install bash), then interrupting with Ctrl+C (when it asks you if you want openssh is a good moment to do this), running `apk add bash` to install bash. And then you can reproduce it.

This is pretty much how I am reproducing this, because I don't have my Alpine laptop with me right now.

**Comment by click0** [comment]
Please show one command:
`date -d yesterday +%s`

**Comment by Michcioperz** [comment]
Also invalid

**Comment by Michcioperz** [comment]
From `date -h`:
```
        -d,--date TIME  Display TIME, not 'now'
```
```
Recognized TIME formats:
        hh:mm[:ss]
        [YYYY.]MM.DD-hh:mm[:ss]
        YYYY-MM-DD hh:mm[:ss]
        [[[[[YY]YY]MM]DD]hh]mm[.ss]
```

It seems that busybox version of `date` just doesn't support this kind of fuzzy date formats at all.

**Comment by click0** [comment]
Sorry, in the morning I will try to raise the virtual machine and make a patch.

**Comment by Michcioperz** [comment]
I think for a better solution you could make use of the fact that `date +%s` works and subtract 24 hours in seconds in bash.

This still wouldn't be fully POSIX compliant, I think, but for a fully correct and portable solution you'd have to replace `date +%s` with [what's in the "Seconds since the epoch" paragraph of this](https://www.etalabs.net/sh_tricks.html) and it's pretty ugly.

**Comment by click0** [comment]
Apply these two commits https://github.com/click0/jinx/commit/3b2ad9e0f98ce3571705373178e25b2dcce6815f https://github.com/click0/jinx/commit/b82a0a27f0b585d83f39e6eaf10df0192d21f1a5.
The problem must be solved.
